require('general')
--require('keymappings')
require('plugins.luaPlugins')
--require('plugins.nvimtree')
--require('plugins.vimplug')
--require('plugins.startify')
--require('coc')
--require('plugins.theme')
